#!/bin/bash
# ============================================================
# PyLess — Interactive Python Learning Platform
# Installer for clean Linux servers (Ubuntu/Debian)
# Copyright (c) 1998-2026 Nick Antonov / Borodachamba Studio
# License: GPL-3.0
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_banner() {
    echo -e "${CYAN}"
    echo "  ╔══════════════════════════════════════════╗"
    echo "  ║         🐍 PyLess Installer              ║"
    echo "  ║  Interactive Python Learning Platform     ║"
    echo "  ║  © 1998-2026 Borodachamba Studio         ║"
    echo "  ╚══════════════════════════════════════════╝"
    echo -e "${NC}"
}

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

check_root() {
    if [ "$EUID" -ne 0 ]; then
        err "Please run as root: sudo bash install.sh"
    fi
}

detect_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO=$ID
        VERSION=$VERSION_ID
    else
        err "Cannot detect Linux distribution"
    fi
    log "Detected: $DISTRO $VERSION"
}

install_deps() {
    log "Installing system dependencies..."
    apt-get update -qq
    apt-get install -y -qq nginx certbot python3-certbot-nginx curl git build-essential python3-dev > /dev/null 2>&1
    log "System dependencies installed"
}

install_node() {
    if command -v node &> /dev/null; then
        log "Node.js already installed: $(node -v)"
    else
        log "Installing Node.js 20..."
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
        apt-get install -y -qq nodejs > /dev/null 2>&1
        log "Node.js installed: $(node -v)"
    fi
}

install_python_deps() {
    log "Installing Python dependencies..."
    pip3 install -r /opt/pyless/requirements.txt -q
    log "Python dependencies installed"
}

setup_app() {
    APP_DIR="/opt/pyless"
    log "Setting up PyLess in $APP_DIR..."

    if [ -d "$APP_DIR" ]; then
        warn "PyLess already exists at $APP_DIR. Updating..."
        cd "$APP_DIR"
        git pull
    else
        git clone https://github.com/borodachamba/PyLess.git "$APP_DIR"
    fi

    cd "$APP_DIR/frontend"
    npm install --silent
    npm run build
    log "Frontend built"
}

setup_env() {
    APP_DIR="/opt/pyless"
    ENV_FILE="$APP_DIR/.env"

    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════${NC}"
    echo -e "${CYAN}  Configuration${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════${NC}"
    echo ""

    # Domain
    read -p "$(echo -e ${CYAN}Domain name [pylesss.example.com]: ${NC})" DOMAIN
    DOMAIN=${DOMAIN:-pylesss.example.com}

    # Groq API Key
    read -p "$(echo -e ${CYAN}Groq API Key (AI tutor, or press Enter to skip): ${NC})" GROQ_KEY
    GROQ_KEY=${GROQ_KEY:-}

    # JWT Secret
    JWT_SECRET=$(openssl rand -hex 32)

    # Admin Code
    read -p "$(echo -e ${CYAN}Admin invite code (for promoting users): ${NC})" ADMIN_CODE
    ADMIN_CODE=${ADMIN_CODE:-admin$(openssl rand -hex 4)}

    cat > "$ENV_FILE" << EOF
# PyLess Environment Configuration
# Generated by install.sh on $(date)

# Domain
DOMAIN=$DOMAIN

# Security
JWT_SECRET=$JWT_SECRET
ADMIN_CODE=$ADMIN_CODE

# AI Tutor (optional)
GROQ_API_KEY=$GROQ_KEY

# Google OAuth (optional — configure in admin panel)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=https://$DOMAIN/api/auth/google/callback

# Database
DB_DIR=$APP_DIR/data

# CORS
CORS_ORIGINS=https://$DOMAIN,http://$DOMAIN
EOF

    mkdir -p "$APP_DIR/data"
    log "Environment configured: $ENV_FILE"
    echo ""
    echo -e "${YELLOW}Admin code: $ADMIN_CODE${NC}"
    echo -e "${YELLOW}Save this! You'll need it to promote the first admin.${NC}"
    echo ""
}

setup_systemd() {
    APP_DIR="/opt/pyless"

    cat > /etc/systemd/system/pyless.service << EOF
[Unit]
Description=PyLess Backend
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=/usr/bin/python3 -m uvicorn backend.main:app --host 127.0.0.1 --port 8000
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable pyless
    log "Systemd service created"
}

setup_nginx() {
    DOMAIN=$1
    APP_DIR="/opt/pyless"

    cat > /etc/nginx/sites-available/pyless << EOF
server {
    listen 80;
    server_name $DOMAIN;

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    # Rate limiting
    limit_req_zone \$binary_remote_addr zone=api:10m rate=30r/s;
    limit_req_zone \$binary_remote_addr zone=ai:10m rate=5r/s;

    # API
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300;
    }

    # AI (stricter)
    location /api/ai/ {
        limit_req zone=ai burst=5 nodelay;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    # WebSocket for video chat
    location /api/video/ws/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }

    # Static assets
    location /assets/ {
        proxy_pass http://127.0.0.1:8000;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # SPA catch-all
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

    ln -sf /etc/nginx/sites-available/pyless /etc/nginx/sites-enabled/pyless
    rm -f /etc/nginx/sites-enabled/default
    nginx -t && systemctl reload nginx
    log "Nginx configured for $DOMAIN"
}

setup_ssl() {
    DOMAIN=$1
    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════${NC}"
    echo -e "${CYAN}  SSL Certificate Setup${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════${NC}"
    echo ""
    echo "Option 1: Cloudflare (Recommended)"
    echo "  - Set DNS A record: $DOMAIN → $(curl -s ifconfig.me)"
    echo "  - Enable Cloudflare proxy (orange cloud)"
    echo "  - SSL mode: Flexible"
    echo "  - No server-side SSL needed!"
    echo ""
    echo "Option 2: Let's Encrypt (certbot)"
    echo ""
    read -p "$(echo -e ${CYAN}Setup SSL with certbot now? [y/N]: ${NC})" SSL_CHOICE

    if [[ "$SSL_CHOICE" =~ ^[Yy]$ ]]; then
        certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN"
        log "SSL certificate installed"
    else
        warn "Skipping SSL. Configure Cloudflare or run certbot later."
        warn "  sudo certbot --nginx -d $DOMAIN"
    fi
}

setup_backup() {
    APP_DIR="/opt/pyless"
    chmod +x "$APP_DIR/scripts/backup.sh"

    # Daily backup cron
    (crontab -l 2>/dev/null; echo "0 2 * * * $APP_DIR/scripts/backup.sh >> /var/log/pyless-backup.log 2>&1") | crontab -
    log "Daily backup cron job installed"
}

print_summary() {
    DOMAIN=$1
    ADMIN_CODE=$2
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════${NC}"
    echo -e "${GREEN}  ✅ PyLess installed successfully!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════${NC}"
    echo ""
    echo -e "  🌐 URL:        ${CYAN}https://$DOMAIN${NC}"
    echo -e "  📁 App:        ${CYAN}/opt/pyless${NC}"
    echo -e "  📊 Database:   ${CYAN}/opt/pyless/data/pylesss.db${NC}"
    echo -e "  📝 Logs:       ${CYAN}/tmp/pyless.log${NC}"
    echo -e "  🔑 Admin code: ${YELLOW}$ADMIN_CODE${NC}"
    echo ""
    echo -e "  Commands:"
    echo -e "    sudo systemctl start pyless    ${CYAN}# Start server${NC}"
    echo -e "    sudo systemctl stop pyless     ${CYAN}# Stop server${NC}"
    echo -e "    sudo systemctl restart pyless  ${CYAN}# Restart${NC}"
    echo -e "    sudo journalctl -u pyless -f   ${CYAN}# View logs${NC}"
    echo ""
    echo -e "  First steps:"
    echo -e "    1. Open ${CYAN}https://$DOMAIN${NC}"
    echo -e "    2. Register an account"
    echo -e "    3. Promote to admin: POST /api/auth/promote with code ${YELLOW}$ADMIN_CODE${NC}"
    echo -e "    4. Configure AI tutor in admin panel (Groq API key)"
    echo ""
    echo -e "  Docs: ${CYAN}/opt/pyless/docs/${NC}"
    echo ""
}

# ============================================================
# Main
# ============================================================
print_banner
check_root
detect_distro

echo ""
echo -e "${CYAN}This installer will:${NC}"
echo "  1. Install system dependencies (nginx, node, python)"
echo "  2. Clone PyLess to /opt/pyless"
echo "  3. Build frontend"
echo "  4. Configure environment"
echo "  5. Setup systemd service"
echo "  6. Configure nginx"
echo "  7. Optional: SSL certificate"
echo ""

read -p "$(echo -e ${CYAN}Continue? [Y/n]: ${NC})" CONFIRM
if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
    echo "Aborted."
    exit 0
fi

install_deps
install_node
setup_app
install_python_deps
setup_env
setup_systemd
setup_nginx "$DOMAIN"
setup_ssl "$DOMAIN"
setup_backup

systemctl start pyless
sleep 2

if curl -s "http://localhost:8000/api/health" > /dev/null 2>&1; then
    print_summary "$DOMAIN" "$ADMIN_CODE"
else
    warn "Server may still be starting. Check: sudo systemctl status pyless"
fi
